---
- name: "[NestedVirt] Enable nested virtualization"
  when:
    - nested_virtualization.enabled
    - nested_virtualization.file is defined
  ansible.builtin.lineinfile:
    path: "{{ nested_virtualization.file }}"
    line: "options kvm-{{ cpu.type }} nested=Y"
    insertbefore: EOF
    create: true
    user: root
    group: root
    mode: 0644
  notify: update_initramfs

- name: "[NestedVirt] Flush Handlers"
  meta: flush_handlers
