---
- name: "[Updates] : Configure apt repos"
  when:
    - repos is defined
    - repos|length >0
  ansible.builtin.apt_repository:
    repo: "{{ item.source }}"
    state: "{{ item.state | default(present) }}"
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - "{{ repos }}"

- name: "[Updates] Upgrade system"
  when: updates.upgrade
  ansible.builtin.apt:
    upgrade: dist

- name: "[Updates] Configure packages"
  when:
    - updates.packages is defined
    - updates.packages|length>0
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - "{{ updates.packages }}"

- name: "[Updates] Cleanup"
  when: updates.cleanup
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
