---
- name: update_initramfs
  become: true
  ansible.builtin.command: update-initramfs -u

- name: update_grub
  become: true
  ansible.builtin.command: update-grub

- name: reset_shell
  become: true
  ansible.builtin.command: reset
